package mathquery

import (
	"syscall/js"
)

// WasmQueryFunctionsStorage stores all functions
var WasmQueryFunctionsStorage = make(map[string]js.Func)

// SetUpFunctionsToVariables register function to case in map
func SetUpFunctionsToVariables() {
	WasmQueryFunctionsStorage["WasmQueryRandomInt"] = js.FuncOf(WasmQueryRandomInt)
	WasmQueryFunctionsStorage["WasmQueryRandomInt32"] = js.FuncOf(WasmQueryRandomInt32)
	WasmQueryFunctionsStorage["WasmQueryRandomInt64"] = js.FuncOf(WasmQueryRandomInt64)
	WasmQueryFunctionsStorage["WasmQueryRandomFloat32"] = js.FuncOf(WasmQueryRandomFloat32)
	WasmQueryFunctionsStorage["WasmQueryRandomFloat64"] = js.FuncOf(WasmQueryRandomFloat64)
	WasmQueryFunctionsStorage["WasmQueryCeil"] = js.FuncOf(WasmQueryCeil)
	WasmQueryFunctionsStorage["WasmQueryFloor"] = js.FuncOf(WasmQueryFloor)
	WasmQueryFunctionsStorage["WasmQueryRound"] = js.FuncOf(WasmQueryRound)
	WasmQueryFunctionsStorage["WasmQueryGamma"] = js.FuncOf(WasmQueryGamma)
	WasmQueryFunctionsStorage["WasmQueryNaN"] = js.FuncOf(WasmQueryNaN)
	WasmQueryFunctionsStorage["WasmQueryMax"] = js.FuncOf(WasmQueryMax)
	WasmQueryFunctionsStorage["WasmQueryMin"] = js.FuncOf(WasmQueryMin)
	WasmQueryFunctionsStorage["WasmQueryPow"] = js.FuncOf(WasmQueryPow)
	WasmQueryFunctionsStorage["WasmQuerySqrt"] = js.FuncOf(WasmQuerySqrt)
	WasmQueryFunctionsStorage["WasmQueryPi"] = js.FuncOf(WasmQueryPi)
	WasmQueryFunctionsStorage["WasmQueryPiAsString"] = js.FuncOf(WasmQueryPiAsString)
	WasmQueryFunctionsStorage["WasmQueryE"] = js.FuncOf(WasmQueryE)
	WasmQueryFunctionsStorage["WasmQueryEAsString"] = js.FuncOf(WasmQueryEAsString)
	WasmQueryFunctionsStorage["WasmQueryPhi"] = js.FuncOf(WasmQueryPhi)
	WasmQueryFunctionsStorage["WasmQueryPhiAsString"] = js.FuncOf(WasmQueryPhiAsString)
	WasmQueryFunctionsStorage["WasmQueryLn2"] = js.FuncOf(WasmQueryLn2)
	WasmQueryFunctionsStorage["WasmQueryLn2AsString"] = js.FuncOf(WasmQueryLn2AsString)
	WasmQueryFunctionsStorage["WasmQueryLn10"] = js.FuncOf(WasmQueryLn10)
	WasmQueryFunctionsStorage["WasmQueryLn10AsString"] = js.FuncOf(WasmQueryLn10AsString)
	WasmQueryFunctionsStorage["WasmQueryLog2E"] = js.FuncOf(WasmQueryLog2E)
	WasmQueryFunctionsStorage["WasmQueryLog10E"] = js.FuncOf(WasmQueryLog10E)
	WasmQueryFunctionsStorage["WasmQuerySqrt2"] = js.FuncOf(WasmQuerySqrt2)
	WasmQueryFunctionsStorage["WasmQuerySqrt2AsString"] = js.FuncOf(WasmQuerySqrt2AsString)
	WasmQueryFunctionsStorage["WasmQueryMaxInt8"] = js.FuncOf(WasmQueryMaxInt8)
	WasmQueryFunctionsStorage["WasmQueryMinInt8"] = js.FuncOf(WasmQueryMinInt8)
	WasmQueryFunctionsStorage["WasmQueryMaxInt16"] = js.FuncOf(WasmQueryMaxInt16)
	WasmQueryFunctionsStorage["WasmQueryMinInt16"] = js.FuncOf(WasmQueryMinInt16)
	WasmQueryFunctionsStorage["WasmQueryMaxInt32"] = js.FuncOf(WasmQueryMaxInt32)
	WasmQueryFunctionsStorage["WasmQueryMinInt32"] = js.FuncOf(WasmQueryMinInt32)
	WasmQueryFunctionsStorage["WasmQuerySqrtPi"] = js.FuncOf(WasmQuerySqrtPi)
	WasmQueryFunctionsStorage["WasmQuerySqrtPiAsString"] = js.FuncOf(WasmQuerySqrtPiAsString)
	WasmQueryFunctionsStorage["WasmQueryIsNaN"] = js.FuncOf(WasmQueryIsNaN)
	WasmQueryFunctionsStorage["WasmQueryJ0"] = js.FuncOf(WasmQueryJ0)
	WasmQueryFunctionsStorage["WasmQueryJ1"] = js.FuncOf(WasmQueryJ1)
	WasmQueryFunctionsStorage["WasmQueryLog"] = js.FuncOf(WasmQueryLog)
	WasmQueryFunctionsStorage["WasmQueryCosh"] = js.FuncOf(WasmQueryCosh)
	WasmQueryFunctionsStorage["WasmQueryInf"] = js.FuncOf(WasmQueryInf)
	WasmQueryFunctionsStorage["WasmQueryLog10"] = js.FuncOf(WasmQueryLog10)
	WasmQueryFunctionsStorage["WasmQueryErf"] = js.FuncOf(WasmQueryErf)
	WasmQueryFunctionsStorage["WasmQueryErfinv"] = js.FuncOf(WasmQueryErfinv)
	WasmQueryFunctionsStorage["WasmQueryErfc"] = js.FuncOf(WasmQueryErfc)
	WasmQueryFunctionsStorage["WasmQueryErfcinv"] = js.FuncOf(WasmQueryErfcinv)
	WasmQueryFunctionsStorage["WasmQueryExp"] = js.FuncOf(WasmQueryExp)
	WasmQueryFunctionsStorage["WasmQueryExp2"] = js.FuncOf(WasmQueryExp2)
	WasmQueryFunctionsStorage["WasmQueryExpm1"] = js.FuncOf(WasmQueryExpm1)
	WasmQueryFunctionsStorage["WasmQueryHypot"] = js.FuncOf(WasmQueryHypot)
	WasmQueryFunctionsStorage["WasmQueryIlogb"] = js.FuncOf(WasmQueryIlogb)
	WasmQueryFunctionsStorage["WasmQueryY0"] = js.FuncOf(WasmQueryY0)
	WasmQueryFunctionsStorage["WasmQueryY1"] = js.FuncOf(WasmQueryY1)
	WasmQueryFunctionsStorage["WasmQueryTanh"] = js.FuncOf(WasmQueryTanh)
	WasmQueryFunctionsStorage["WasmQueryTrunc"] = js.FuncOf(WasmQueryTrunc)
	WasmQueryFunctionsStorage["WasmQueryTan"] = js.FuncOf(WasmQueryTan)
	WasmQueryFunctionsStorage["WasmQueryAbs"] = js.FuncOf(WasmQueryAbs)
	WasmQueryFunctionsStorage["WasmQueryAcos"] = js.FuncOf(WasmQueryAcos)
	WasmQueryFunctionsStorage["WasmQueryAcosh"] = js.FuncOf(WasmQueryAcosh)
	WasmQueryFunctionsStorage["WasmQueryAsin"] = js.FuncOf(WasmQueryAsin)
}
